export const FAKE_COURSES = [
  {
    id: 1,
    title: "React Mastery: From Zero to Hero",
    instructor: "Sarah Chen",
    instructorId: 1,
    price: 89.99,
    rating: 4.8,
    students: 12430,
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop",
    category: "Development",
    level: "Beginner",
    duration: "42h",
    lessons: 186,
    bestseller: true,
    description: "Master React from fundamentals to advanced patterns including hooks, context, and performance optimization.",
  },
  {
    id: 2,
    title: "UI/UX Design Fundamentals",
    instructor: "Marcus Rivera",
    instructorId: 2,
    price: 74.99,
    rating: 4.9,
    students: 9821,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    category: "Design",
    level: "Beginner",
    duration: "28h",
    lessons: 124,
    bestseller: true,
    description: "Learn design thinking, Figma, and user research to build beautiful products users love.",
  },
  {
    id: 3,
    title: "Python for Data Science",
    instructor: "Dr. Aisha Patel",
    instructorId: 3,
    price: 94.99,
    rating: 4.7,
    students: 18902,
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=225&fit=crop",
    category: "Data Science",
    level: "Intermediate",
    duration: "56h",
    lessons: 203,
    bestseller: false,
    description: "Comprehensive Python data science course covering pandas, numpy, matplotlib, and machine learning basics.",
  },
  {
    id: 4,
    title: "AWS Cloud Practitioner Certification",
    instructor: "James Kim",
    instructorId: 4,
    price: 109.99,
    rating: 4.6,
    students: 7654,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=225&fit=crop",
    category: "Cloud",
    level: "Beginner",
    duration: "34h",
    lessons: 145,
    bestseller: false,
    description: "Prepare for AWS Cloud Practitioner exam with hands-on labs and practice tests.",
  },
  {
    id: 5,
    title: "Advanced JavaScript & ES2024",
    instructor: "Emma Watson",
    instructorId: 5,
    price: 79.99,
    rating: 4.8,
    students: 14300,
    image: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=400&h=225&fit=crop",
    category: "Development",
    level: "Advanced",
    duration: "38h",
    lessons: 168,
    bestseller: true,
    description: "Deep dive into modern JavaScript including async patterns, modules, and cutting-edge ES2024 features.",
  },
  {
    id: 6,
    title: "Machine Learning with TensorFlow",
    instructor: "Dr. Aisha Patel",
    instructorId: 3,
    price: 119.99,
    rating: 4.7,
    students: 6543,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop",
    category: "AI/ML",
    level: "Advanced",
    duration: "64h",
    lessons: 241,
    bestseller: false,
    description: "Build neural networks, CNNs, and NLP models with TensorFlow and Keras.",
  },
  {
    id: 7,
    title: "Digital Marketing Masterclass",
    instructor: "Sofia Martinez",
    instructorId: 6,
    price: 69.99,
    rating: 4.5,
    students: 22100,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    category: "Marketing",
    level: "Beginner",
    duration: "24h",
    lessons: 98,
    bestseller: true,
    description: "Master SEO, social media, email marketing, and analytics to grow any business online.",
  },
  {
    id: 8,
    title: "Node.js & Express API Development",
    instructor: "Sarah Chen",
    instructorId: 1,
    price: 84.99,
    rating: 4.9,
    students: 8921,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=225&fit=crop",
    category: "Development",
    level: "Intermediate",
    duration: "44h",
    lessons: 192,
    bestseller: false,
    description: "Build scalable REST APIs with Node.js, Express, MongoDB, and authentication systems.",
  },
];

export const FAKE_CATEGORIES = [
  "Development",
  "Design",
  "Data Science",
  "Cloud",
  "AI/ML",
  "Marketing",
  "Business",
  "Photography",
];

export const FAKE_LESSONS = [
  { id: 1, section: "Introduction", title: "Welcome & Course Overview", duration: "5:30", completed: true, type: "video" },
  { id: 2, section: "Introduction", title: "Setting Up Your Environment", duration: "12:45", completed: true, type: "video" },
  { id: 3, section: "Introduction", title: "Introduction Quiz", duration: "5:00", completed: false, type: "quiz" },
  { id: 4, section: "Core Concepts", title: "Understanding JSX", duration: "18:20", completed: false, type: "video" },
  { id: 5, section: "Core Concepts", title: "Components & Props", duration: "22:10", completed: false, type: "video" },
  { id: 6, section: "Core Concepts", title: "State & Lifecycle", duration: "25:45", completed: false, type: "video" },
  { id: 7, section: "Core Concepts", title: "Core Concepts Quiz", duration: "10:00", completed: false, type: "quiz" },
  { id: 8, section: "Hooks", title: "useState & useEffect", duration: "30:20", completed: false, type: "video" },
  { id: 9, section: "Hooks", title: "useContext & useReducer", duration: "28:55", completed: false, type: "video" },
  { id: 10, section: "Hooks", title: "Custom Hooks", duration: "20:30", completed: false, type: "video" },
];

export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What is JSX in React?",
    options: ["A JavaScript syntax extension", "A CSS framework", "A database query language", "A testing library"],
    answer: 0,
  },
  {
    id: 2,
    question: "Which hook is used for side effects?",
    options: ["useState", "useEffect", "useContext", "useReducer"],
    answer: 1,
  },
  {
    id: 3,
    question: "What does virtual DOM mean?",
    options: ["A physical server", "An in-memory representation of the real DOM", "A CSS property", "A React component"],
    answer: 1,
  },
];

export const FAKE_STUDENTS_ENROLLED = [
  { id: 1, name: "Alex Johnson", email: "alex@email.com", avatar: "AJ", course: "React Mastery", progress: 78, enrolled: "2025-01-15", status: "active" },
  { id: 2, name: "Maria Garcia", email: "maria@email.com", avatar: "MG", course: "React Mastery", progress: 45, enrolled: "2025-02-01", status: "active" },
  { id: 3, name: "David Lee", email: "david@email.com", avatar: "DL", course: "React Mastery", progress: 92, enrolled: "2024-12-10", status: "completed" },
  { id: 4, name: "Emma Wilson", email: "emma@email.com", avatar: "EW", course: "React Mastery", progress: 12, enrolled: "2025-03-01", status: "active" },
];

export const REVENUE_DATA = [
  { month: "Jan", revenue: 4200 },
  { month: "Feb", revenue: 5800 },
  { month: "Mar", revenue: 7200 },
  { month: "Apr", revenue: 6100 },
  { month: "May", revenue: 8900 },
  { month: "Jun", revenue: 9400 },
  { month: "Jul", revenue: 11200 },
  { month: "Aug", revenue: 10100 },
];

export const ADMIN_USERS = [
  { id: 1, name: "Sarah Chen", email: "sarah@edu.com", role: "instructor", status: "active", courses: 5, joined: "2024-01-15" },
  { id: 2, name: "Alex Student", email: "alex@email.com", role: "student", status: "active", courses: 3, joined: "2024-06-20" },
  { id: 3, name: "Dr. Patel", email: "patel@edu.com", role: "instructor", status: "active", courses: 8, joined: "2023-11-05" },
  { id: 4, name: "Jane Doe", email: "jane@email.com", role: "student", status: "suspended", courses: 1, joined: "2025-01-01" },
];

export const PENDING_COURSES = [
  { id: 1, title: "Vue.js Complete Guide", instructor: "Tom Brown", submitted: "2025-03-01", status: "pending", category: "Development" },
  { id: 2, title: "Photoshop for Beginners", instructor: "Lucy Art", submitted: "2025-03-02", status: "pending", category: "Design" },
  { id: 3, title: "Business Strategy 101", instructor: "CEO Mike", submitted: "2025-02-28", status: "pending", category: "Business" },
];

export const COURSE_PROGRESS = { 1: 65, 2: 0, 3: 30, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 };
